debug: false

# 系统配置
server:
  port: 8081
  compression:
    enabled: false

# 日志配置
logging:
  level:
    com:
      yanzhen:
        mapper: debug

# 令牌配置
jwt:
  token:
    header:
      name: tracejp
      object: saya
    expired: 100000000
    sign: saya

# 本地文件存储路径配置，可以通过配置local.file.enable=false关闭本地文件处理器
local:
  file:
    # 头像保存目录
    user-avatar:
    # 文件保存目录
    file-save:
    # 临时文件存储目录
    file-tmp:

# 阿里-第三方配置
ali:
  sms:
    access-key-id:
    access-key-secret:
    endpoint:
    sign-name:
    template-code:
      # 登录短信模板
      login:
      # 修改手机短信模板
      updatePhone:
  oss:
    enable: true
    access-key-id:
    access-key-secret:
    endpoint:
    bucketName:

# spring整合配置
spring:
  # 热部署
  devtools:
    restart:
      enabled: true

  # json转换配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saya?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username:
    password:
    # druid连接池配置
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # web监控页
      StatViewServlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456

  # redis配置
  redis:
    database: 1
    host:
    port: 6379
    password:

  servlet:
    # 文件上传配置
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 30MB

#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  # sql日志打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#swagger配置
swagger2:
  enable: true
  title: 纱耶网盘
  description: 仿阿里云盘项目
  version: 1.0.0
  serviceUrl: https://github.com/traceJP
  basePackage: com.tracejp.saya.controller
